kill_rewards:
  mob_kill_commands:
    - "say You have deleted a mob!"
    - "give %player% diamond 1"
    - "eco give %player% 100"
  player_kill_commands:
    - "say %player% has eliminated %victim%!"
    - "give %player% diamond 3"
    - "eco give %player% 200"
    
messages:
  version-message: "&aThe version of %plugin% is %version%"
  no-permission-message: "&cYou do not have permission to execute this command."
  reload-message: "&aReloaded."
    