kill_rewards:
  mob_kill_commands:
    - "say ¡Has eliminado un mob!"
    - "give %player% diamond 1"
    - "eco give %player% 100"
  player_kill_commands:
    - "say %player% ha eliminado a %victim%!"
    - "give %player% diamond 3"
    - "eco give %player% 200"
